config/routes.rb
Rails.application.routes.draw do
  get 'thank/you'
  resources :ingredients
  get 'ingredients/index'
  root 'ingredients#index'
  get 'checkout/index'
  get 'checkout/thank'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def index 
        @ingredients = Ingredient.all
    end
    def thank
    end
    def counter
        @ingredients = Ingredient.all
        count = 0;
        for i in @ingredients
            count = count + ingredients.quantity;
        end
        return count;

    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end


  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to root_url, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to root_url, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def checkout
    @ingredients = Ingredient.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity, :completed)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/thank_helper.rb
module ThankHelper
end

app/views/checkout/index.html.erb
<h1>Price</h1>

<table class ="table table-sm table-light" >
  <thead class = "thead-light">
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Contains</th>
      <th>Cost</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
        
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.quantity %></td>
          <td><%= ingredient.completed %></td>
          <td><%= '$1.00' %> </td>
        </tr>
    <% end %>
        <tr class="table-warning">
        <td></td>
        <td></td>
        <td><strong>Total Cost: </strong></td>
        <td>$<%= @ingredients.sum(:quantity) %>.00</td>
        </tr>
  </tbody>
</table>

<%= link_to 'Back', ingredients_path, class: 'btn btn-danger' %>
<a href='thank' class = 'btn btn-success'>Pay</a>

app/views/checkout/thank.html.erb
<h1>Thanks for shopping with us!</h1>
<p>Your order will be ready in 30 minutes.</p>
<blockquote class="blockquote text-center">
    <%= image_tag("https://media1.giphy.com/media/xUOxeRP7tdqPm1M4CI/source.gif", :size => "300x300") %>
</blockquote>

app/views/ingredients/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class = "alert alert-warning alert-dismissible">
    <button class = "close" data-dismiss = "alert">
        <small><sup>x</sup></small>
    </button>
    <%= content_tag(:div, msg) %>
    </div>
<% end %>        

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form">
  <%= form.label :name %>
  <%= form.select :name,  ["Sesame Bun", "Beef Patty","Grilled Chicken", "Fried Chicken", "Lettuce", "Tomatoes", "Pickles", "Ham","Turkey"] %>
  </div>


  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed  %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient<%= image_tag("https://thumbs.gfycat.com/GoodnaturedShimmeringHuia-small.gif", :size => "150x150") %></h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient , class: 'btn btn-primary'%> |
<%= link_to 'Back', ingredients_path, class: 'btn btn-danger' %>

app/views/ingredients/index.html.erb
<blockquote class="blockquote text-right">
<p class="lead">"The Best Burgers in the World"</p>
<footer class="blockquote-footer">Alexander Wong</footer>
<%= image_tag("https://media0.giphy.com/media/i4bWPx9KZWeMph3ZLv/source.gif", :size => "100x100") %>
</blockquote>
<h2>Burger</h2>
<table class ="table table-hover" >
  <thead class = "thead-dark">
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Contains</th>
      <th>Cost</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
        
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.quantity %></td>
          <td><%= ingredient.completed %></td>
          <td><%= '$1.00' %> </td>
          <td><%= link_to 'Show', ingredient, class: 'btn btn-outline-primary' %></td>
          <td><%= link_to 'Edit', edit_ingredient_path(ingredient), class: 'btn btn-outline-secondary'%></td>
          <td><%= button_to "Delete", ingredient, class: 'btn btn-outline-danger', :method => :delete%></td>
        </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path, class: 'btn btn-info' %>
<a href='checkout/index' class = 'btn btn-success'>Checkout</a>

<blockquote class="blockquote text-right"><%= image_tag("https://thumbs.gfycat.com/FatherlyPointedAracari-max-1mb.gif", :size => "100x100") %></blockquote>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render 'form', ingredient: @ingredient %>
<%= link_to 'Back', ingredients_path, class: 'btn btn-outline-danger' %>

<blockquote class="blockquote text-right"><%= image_tag("https://media.giphy.com/media/hV0D15h8onMn9Pn6e7/giphy.gif", :size => "200x250") %></blockquote>

app/views/ingredients/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ingredient.quantity %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @ingredient.completed %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient), class: 'btn btn-warning'%> |
<%= link_to 'Back', ingredients_path , class: 'btn btn-info'%>

<blockquote class="blockquote text-center"><%= image_tag("https://classroomclipart.com/images/gallery/Animations/Food/animated-clipart-gif-building-cheese-burger-animation-05c.gif", :size => "450x450") %></blockquote>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatBurger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="https://media0.giphy.com/media/tITrMyC7dvgssM02b2/source.gif">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="welcome if action_name == 'welcome'">
    <%= render "lists/navbar" %>
    <div class= "container">
    <%= render "ingredients/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <a class="navbar-brand" href="#"><%= image_tag("https://thumbs.gfycat.com/FrenchWiltedKawala-small.gif", :size => "50x50") %>CatBurger</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.quantity %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @list.quantity %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>